services:
  domain-monitor:
    build: .
    ports:
      - "9394:9394"
    environment:
      - RUBY_ENV=production
      - NACOS_ADDR=http://192.168.1.19:8848
      - NACOS_NAMESPACE=devops
      - NACOS_GROUP=DEFAULT_GROUP
      - NACOS_DATA_ID=domain-monitor.yml
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=nacos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9394/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - domain-monitor-net

networks:
  domain-monitor-net:
    driver: bridge