services:
  domain-monitor:
    build: .
    env_file:
      - .env
    ports:
      - "9394:9394"
    environment:
      - RUBY_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9394/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - domain-monitor-net

networks:
  domain-monitor-net:
    driver: bridge