{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "domain-monitor.fullname" . }}
  labels:
    {{- include "domain-monitor.labels" . | nindent 4 }}
spec:
  host: {{ include "domain-monitor.fullname" . }}
  trafficPolicy:
    {{- toYaml .Values.istio.destinationRule.trafficPolicy | nindent 4 }}
  subsets:
  - name: v1
    labels:
      version: {{ .Values.image.tag | default .Chart.AppVersion }}
    trafficPolicy:
      portLevelSettings:
      - port:
          number: {{ .Values.service.port }}
        loadBalancer:
          simple: ROUND_ROBIN
{{- end }}