{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "domain-monitor.fullname" . }}-gateway
  labels:
    {{- include "domain-monitor.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.istio.gateway.selector | nindent 4 }}
  servers:
    {{- toYaml .Values.istio.gateway.servers | nindent 4 }}
{{- end }}