{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "domain-monitor.fullname" . }}
  labels:
    {{- include "domain-monitor.labels" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  gateways:
    {{- range .Values.istio.virtualService.gateways }}
    - {{ include "domain-monitor.fullname" $ }}-{{ . }}
    {{- end }}
  http:
    - match:
      - uri:
          prefix: /health
      route:
      - destination:
          host: {{ include "domain-monitor.fullname" . }}
          port:
            number: {{ .Values.service.port }}
      headers:
        response:
          add:
            x-health-check: "true"
    - match:
      - uri:
          prefix: /metrics
      route:
      - destination:
          host: {{ include "domain-monitor.fullname" . }}
          port:
            number: {{ .Values.service.port }}
      headers:
        response:
          add:
            x-metrics: "true"
    {{- range .Values.istio.virtualService.http }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
    fault:
      delay:
        percentage:
          value: 0.1
        fixedDelay: 5s
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx,reset,connect-failure,refused-stream
{{- end }}