apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "domain-monitor.fullname" . }}-gateway
  labels:
    {{- include "domain-monitor.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway # 可通过 values.yaml 配置 selector
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.hosts }}
        - {{ . | quote }}
        {{- end }}