{{- if .Values.harbor.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}