apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-charts.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    monitor: "true"
    {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm-charts.selectorLabels" . | nindent 4 }}