apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: domain-monitor-telemetry
  namespace: domain-monitor
  labels:
    app: domain-monitor
spec:
  metrics:
  - providers:
    - name: prometheus
  - overrides:
    - match:
        metric: ALL_METRICS
        mode: CLIENT
      tagOverrides:
        destination_service_name:
          value: "domain-monitor"
        destination_service_namespace:
          value: "domain-monitor"
  accessLogging:
  - providers:
    - name: otel
    - name: envoy
  tracing:
  - providers:
    - name: jaeger